enum UserDefaultsKeys {
    static let selectedTheme = "selectedTheme"
    static let selectedAvatar = "selectedAvatar"
    static let sessions = "sessions"
    static let hasShownDemoSessions = "hasShownDemoSessions"
    static let poorPostureThreshold = "poorPostureThreshold"
    static let normalAirPodsAngle = "normalAirPodsAngle"
    static let isHapticFeedbackEnabled = "isHapticFeedbackEnabled"
    static let isBadPostureHapticEnabled = "isBadPostureHapticEnabled"
    static let isWarningCountdownEnabled = "isWarningCountdownEnabled"
    static let isRecoveryCountdownEnabled = "isRecoveryCountdownEnabled"
    static let notificationMode = "notificationMode"
    static let realtimeNotificationDelay = "realtimeNotificationDelay"
    static let audioCueStyle = "audioCueStyle"
    static let hasCompletedOnboarding = "hasCompletedOnboarding"
    static let enhancedAirPodsDetectionEnabled = "enhancedAirPodsDetectionEnabled"
    static let repCountingSettings = "stretchSettings"
    static let stretchVoiceEnabled = "stretchVoiceEnabled"
    static let stretchHapticEnabled = "stretchHapticEnabled"
    static let stretchShowRepCount = "stretchShowRepCount"
    static let stretchTargetReps = "stretchTargetReps"
    static let backgroundSessionState = "background_session_state"
}
